#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef CROWDCONNECTEDCORE_SWIFT_H
#define CROWDCONNECTEDCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CrowdConnectedCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class Credentials;
enum LocationTrackingMode : NSInteger;
@class NSString;
/// SDK Configuration containing authentication Credentials and tracking mode.
/// The Configuration class encapsulates all settings required to initialize and run
/// the CrowdConnected SDK. It includes authentication credentials, enabled modules,
/// and location tracking behavior.
/// <em>Usage:</em>
/// Create a Configuration using the fluent Builder pattern:
/// \code
/// let config = Configuration.Builder()
///     .withCredentials(appKey: "your-app-key",
///                      clientId: "your-client-id",
///                      clientSecret: "your-client-secret")
///     .with(modules: [.geo, .ips])
///     .with(trackingMode: .background)
///     .build()
///
/// \endcodeOr use the direct initializer if you already have Credentials:
/// \code
/// let credentials = Credentials(appKey: "key", clientId: "id", clientSecret: "secret")
/// let config = Configuration(credentials: credentials, modules: [.geo], trackingMode: .foreground)
///
/// \endcode
SWIFT_CLASS("_TtC18CrowdConnectedCore13Configuration")
@interface Configuration : NSObject
/// The authentication credentials provided by CrowdConnected.
/// These are required to authenticate API requests and should be kept secure.
@property (nonatomic, readonly, strong) Credentials * _Nonnull credentials;
/// The location tracking mode determining foreground and background tracking behavior.
/// Controls whether location tracking is active in the background, foreground, or both.
@property (nonatomic, readonly) enum LocationTrackingMode trackingMode;
/// Optional custom fields for internal use.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull customFields;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum Module : NSInteger;
/// Builder for creating Configuration objects with a fluent, chainable API.
/// The Builder pattern provides a cleaner and more readable way to construct
/// Configuration objects with all required credentials and optional settings.
/// <em>Features:</em>
/// <ul>
///   <li>
///     Fluent API with method chaining for easy configuration
///   </li>
///   <li>
///     Consolidated credential setter for all authentication parameters
///   </li>
///   <li>
///     Default values for optional parameters
///   </li>
///   <li>
///     Single or bulk module addition
///   </li>
///   <li>
///     Automatic duplicate module prevention
///   </li>
///   <li>
///     Validation in build() to ensure all required credentials are set
///   </li>
/// </ul>
/// <em>Example usage:</em>
/// \code
/// // Full configuration with all credentials and modules
/// let config = Configuration.Builder()
///     .withCredentials(appKey: "app-456",
///                      clientId: "client-789",
///                      clientSecret: "secret-abc")
///     .with(modules: [.geo, .ips])
///     .with(trackingMode: .background)
///     .build()
///
/// // Add modules incrementally
/// let customConfig = Configuration.Builder()
///     .withCredentials(appKey: "app-456",
///                      clientId: "client-789",
///                      clientSecret: "secret-abc")
///     .with(module: .geo)
///     .with(module: .ips)
///     .build()
///
/// \endcode
SWIFT_CLASS("_TtCC18CrowdConnectedCore13Configuration7Builder")
@interface Builder : NSObject
/// Creates a new Builder instance for constructing Configuration objects.
/// Initializes a Builder with all optional properties unset. You must call
/// withCredentials() to set authentication credentials before calling build(),
/// or a fatal error will be raised.
/// Other properties have sensible defaults:
/// <ul>
///   <li>
///     modules: Empty array (no modules enabled)
///   </li>
///   <li>
///     trackingMode: .foreground (only track when app is in foreground)
///   </li>
/// </ul>
/// <em>Typical usage:</em>
/// \code
/// let config = Configuration.Builder()
///     .withCredentials(appKey: "key", clientId: "id", clientSecret: "secret")
///     .with(module: .geo)
///     .build()
///
/// \endcode
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Sets all required authentication credentials in one call.
/// This method consolidates all credential parameters (appKey, clientId, clientSecret)
/// into a single Credentials object. Must be called before build() to successfully
/// create a Configuration.
/// \param appKey Your unique application key provided by CrowdConnected.
///
/// \param clientId Your unique client ID provided by CrowdConnected for API authentication.
///
/// \param clientSecret Your unique client secret provided by CrowdConnected for API authentication.
/// Keep this value secure and never hardcode it in production code.
///
///
/// returns:
/// Self for method chaining, allowing fluent API usage.
- (Builder * _Nonnull)withCredentialsWithAppKey:(NSString * _Nonnull)appKey clientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret;
/// Adds or removes a single module from the configuration’s module list.
/// Use this method to add or remove modules one at a time. Multiple calls will append
/// each module to the existing list or remove it as specified, allowing incremental
/// module setup and modification.
/// <em>Behavior:</em>
/// <ul>
///   <li>
///     When <code>enabled</code> is <code>true</code> (default): Adds the module to the list if not already present.
///     Duplicate modules are automatically prevented.
///   </li>
///   <li>
///     When <code>enabled</code> is <code>false</code>: Removes all instances of the module from the list.
///   </li>
/// </ul>
/// <em>Examples:</em>
/// \code
/// // Add modules
/// builder.with(module: .geo)           // Add geo module (enabled=true by default)
/// builder.with(module: .ips, enabled: true)   // Explicitly add IPS module
///
/// // Remove modules
/// builder.with(module: .geo, enabled: false)  // Remove geo module
///
/// \endcode\param module A single Module instance to add or remove from the configuration.
///
/// \param enabled Boolean flag indicating whether to add (true) or remove (false) the module.
/// Defaults to true (add the module).
///
///
/// returns:
/// Self for method chaining, allowing fluent API usage.
- (Builder * _Nonnull)withModule:(enum Module)module_ enabled:(BOOL)enabled;
/// Sets the location tracking mode for the SDK.
/// This determines whether the SDK tracks user location in foreground,
/// background, or both scenarios. The default is foreground-only tracking.
/// \param trackingMode The desired LocationTrackingMode.
///
///
/// returns:
/// Self for method chaining, allowing fluent API usage.
- (Builder * _Nonnull)withTrackingMode:(enum LocationTrackingMode)trackingMode;
/// Sets a custom fields for internal use.
/// \param customFields The custom fields.
///
///
/// returns:
/// Self for method chaining, allowing fluent API usage.
- (Builder * _Nonnull)withCustomFields:(NSDictionary<NSString *, NSString *> * _Nonnull)customFields;
/// Builds and returns the configured Configuration object.
/// This method finalizes the builder and creates an immutable Configuration
/// instance with all the settings specified through the builder methods.
/// After a successful call to build(), the Configuration object is ready to be
/// passed to the SDK’s start method.
/// <em>Validation:</em>
/// This method performs validation to ensure credentials have been set:
/// <ul>
///   <li>
///     withCredentials() must be called before build()
///   </li>
/// </ul>
/// If credentials have not been set, this method will raise a fatal error
/// indicating that credentials are required.
/// <em>Return Value:</em>
/// A fully configured Configuration object with:
/// <ul>
///   <li>
///     credentials: Set via withCredentials()
///   </li>
///   <li>
///     modules: Set via with(modules:) or with(module:), defaults to empty array
///   </li>
///   <li>
///     trackingMode: Set via with(trackingMode:), defaults to .foreground
///   </li>
/// </ul>
///
/// throws:
/// Fatal error if credentials have not been set via withCredentials().
///
/// returns:
/// A fully configured Configuration object.
- (Configuration * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end

/// Pixel coordinates representing a location on a 2D floor plan.
SWIFT_CLASS("_TtC18CrowdConnectedCore10Coordinate")
@interface Coordinate : NSObject
/// The x coordinate of the location in pixels.
@property (nonatomic) double xPixels;
/// The y coordinate of the location in pixels.
@property (nonatomic) double yPixels;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Authentication Credentials used for the CrowdConnected SDK.
/// All credential values are provided by CrowdConnected.
SWIFT_CLASS("_TtC18CrowdConnectedCore11Credentials")
@interface Credentials : NSObject
/// Creates a new credentials object.
/// \param appKey The unique app key provided by CrowdConnected.
///
/// \param clientId The client ID provided by CrowdConnected.
///
/// \param clientSecret The client secret key provided by CrowdConnected.
///
- (nonnull instancetype)initWithAppKey:(NSString * _Nonnull)appKey clientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol CrowdConnectedDelegate;
@class Location;
/// The entry point class of the <code>CrowdConnected</code> SDK.
SWIFT_CLASS("_TtC18CrowdConnectedCore14CrowdConnected")
@interface CrowdConnected : NSObject
/// A <code>CrowdConnectedDelegate</code> delegate used to return location data produced by the <code>CrowdConnected</code> SDK.
/// The delegate receives callbacks for:
/// <ul>
///   <li>
///     <code>locationProvider(_:didStartSuccess:)</code> — called when SDK starts successfully
///   </li>
///   <li>
///     <code>locationProvider(_:didStartFailure:)</code> — called if SDK start fails
///   </li>
///   <li>
///     <code>locationProvider(_:didUpdateLocation:)</code> — called when new location data is available
///   </li>
/// </ul>
/// Doesn’t need to be set if location updates are not expected or used by your app. Defaults to <code>nil</code>.
@property (nonatomic, weak) id <CrowdConnectedDelegate> _Nullable delegate;
/// The shared <code>CrowdConnected</code> instance.
/// Used for SDK configurations and communication.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CrowdConnected * _Nonnull shared;)
+ (CrowdConnected * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// The associated CrowdConnected device ID.
/// Available after the SDK has been started successfully.
@property (nonatomic, readonly, copy) NSString * _Nullable deviceID;
/// Check if the SDK is currently running and successfully started.
///
/// returns:
/// <code>true</code> if SDK is running, <code>false</code> otherwise.
@property (nonatomic, readonly) BOOL isRunning;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Get the SDK version.
///
/// returns:
/// The SDK version string in the format “version(build)”.
+ (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// Start the SDK.
/// Initiates the SDK lifecycle including authentication, device registration, and module activation.
/// When this method is called:
/// <ul>
///   <li>
///     If SDK is already running, the request is rejected.
///   </li>
///   <li>
///     If SDK is transitioning (start/stop in progress), the request is queued and will execute when the current transition completes.
///   </li>
///   <li>
///     Otherwise, the start process begins: credentials are validated, device registers with the server, and modules are activated.
///   </li>
/// </ul>
/// The start operation is asynchronous. Results are reported through the delegate:
/// <ul>
///   <li>
///     <code>locationProvider(_:didStartSuccess:)</code> is called when the SDK starts successfully with the device ID.
///   </li>
///   <li>
///     <code>locationProvider(_:didStartFailure:)</code> is called if the SDK fails to start with an error code.
///   </li>
///   <li>
///     Once started, <code>locationProvider(_:didUpdateLocation:)</code> will be called with location updates as they arrive.
///   </li>
/// </ul>
/// \param configuration The SDK configuration containing authentication credentials, enabled modules, and tracking mode.
///
- (void)startWith:(Configuration * _Nonnull)configuration;
/// Stop the SDK and all its processes.
/// Stops all SDK operations including location tracking, data publishing, and background monitoring.
/// The stop operation is asynchronous and serialized through the lifecycle queue.
/// Call this method when you no longer need location tracking, such as on app termination or when
/// transitioning to a state that doesn’t require the SDK.
- (void)stop;
/// Set and persist an alias for the current device.
/// \param key The alias key.
///
/// \param value The alias value.
///
- (void)setAliasWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
/// Get the last known location from the SDK.
///
/// returns:
/// The last known location, or <code>nil</code> if no location has been received yet.
- (Location * _Nullable)getLastLocation SWIFT_WARN_UNUSED_RESULT;
/// Get the current SDK configuration.
///
/// returns:
/// The SDK configuration, or <code>nil</code> if the SDK hasn’t been started yet.
- (Configuration * _Nullable)getCurrentConfiguration SWIFT_WARN_UNUSED_RESULT;
@end

@protocol SimulationCallback;
@interface CrowdConnected (SWIFT_EXTENSION(CrowdConnectedCore))
/// Activates a simulation session using the provided JWT token.
/// The SDK must already be started before calling this method.
/// A second call replaces any existing session (the previous one is deactivated first).
/// since:
/// 3.1.0
/// \param token A signed JWT containing the <code>sid</code> (session ID) and <code>exp</code> claims.
///
- (void)activateSimulationWithToken:(NSString * _Nonnull)token;
/// Activates a simulation session with an optional callback for session events.
/// The SDK must already be started before calling this method.
/// A second call replaces any existing session (the previous one is deactivated first).
/// All callbacks fire on a background thread — marshal to the main thread if you need to update UI.
/// since:
/// 3.1.0
/// \param token A signed JWT containing the <code>sid</code> (session ID) and <code>exp</code> claims.
///
/// \param callback An optional object that receives connection, error, and disconnection events.
///
- (void)activateSimulationWithToken:(NSString * _Nonnull)token callback:(id <SimulationCallback> _Nullable)callback;
/// Stops any active simulation session.
/// Safe to call at any time, including when no session is active.
/// <code>onSimulationDisconnected</code> is <em>not</em> called when you stop the session explicitly.
/// since:
/// 3.1.0
- (void)deactivateSimulation;
@end

enum ErrorCode : NSInteger;
/// A delegate protocol for receiving callbacks from the CrowdConnected SDK.
/// Implement this protocol to receive location updates, success notifications, and error callbacks from the SDK.
/// All methods are optional.
SWIFT_PROTOCOL("_TtP18CrowdConnectedCore22CrowdConnectedDelegate_")
@protocol CrowdConnectedDelegate
@optional
/// Called when new locations have been computed by the SDK.
/// \param crowdConnected The <code>CrowdConnected</code> instance that generated the update.
///
/// \param locations An array of <code>Location</code> items in chronological order.
///
- (void)locationProvider:(CrowdConnected * _Nonnull)crowdConnected didUpdateLocation:(Location * _Nonnull)location;
/// Called when the SDK has successfully started and registered the device.
/// \param crowdConnected The <code>CrowdConnected</code> instance that completed initialization.
///
/// \param deviceId The unique device identifier assigned by the CrowdConnected backend.
///
- (void)locationProvider:(CrowdConnected * _Nonnull)crowdConnected didStartSuccess:(NSString * _Nonnull)deviceId;
/// Called when an error occurs in the SDK.
/// \param crowdConnected The <code>CrowdConnected</code> instance where the error occurred.
///
/// \param errorCode A <code>ErrorCode</code> describing the error that occurred.
///
- (void)locationProvider:(CrowdConnected * _Nonnull)crowdConnected didStartFailure:(enum ErrorCode)errorCode;
@end

/// Validation result for SDK Configuration and startup.
/// Use the <code>description</code> property for detailed Error messages.
typedef SWIFT_ENUM(NSInteger, ErrorCode, open) {
/// SDK configuration and startup completed successfully.
  ErrorCodeNoError = 0,
/// SDK is already running and cannot be started again.
  ErrorCodeAlreadyRunning = 1,
/// App key is missing or empty in the credentials.
  ErrorCodeMissingAppKey = 2,
/// Token is missing or empty in the credentials.
  ErrorCodeMissingToken = 3,
/// Secret is missing or empty in the credentials.
  ErrorCodeMissingSecret = 4,
/// Device registration with the CrowdConnected backend failed.
  ErrorCodeDeviceRegistrationFailed = 5,
/// No SDK modules (Geo or IPS) are active.
  ErrorCodeNoModulesAreActive = 6,
/// <code>NSBluetoothAlwaysUsageDescription</code> is missing from Info.plist.
  ErrorCodeMissingBluetoothPermissionItem = 7,
/// <code>NSLocationWhenInUseUsageDescription</code> is missing from Info.plist.
  ErrorCodeMissingWhileInUseLocationPermissionItem = 8,
/// <code>NSLocationAlwaysAndWhenInUseUsageDescription</code> is missing from Info.plist.
  ErrorCodeMissingAlwaysLocationPermissionItem = 9,
/// <code>location</code> entry is missing from <code>UIBackgroundModes</code> in Info.plist.
  ErrorCodeMissingLocationBackgroundModeItem = 10,
/// <code>bluetooth-central</code> entry is missing from <code>UIBackgroundModes</code> in Info.plist.
  ErrorCodeMissingBluetoothBackgroundModeItem = 11,
  ErrorCodeNoGeoModuleImported = 15,
  ErrorCodeNoIPSModuleImported = 17,
  ErrorCodeNoCoreBluetoothModuleImported = 19,
};
static NSString * _Nonnull const ErrorCodeDomain = @"CrowdConnectedCore.ErrorCode";

/// A location computed by the CrowdConnected SDK.
/// Contains geographic coordinates, metric positions, floor information, timestamps, and quality indicators.
SWIFT_CLASS("_TtC18CrowdConnectedCore8Location")
@interface Location : NSObject
/// The x coordinate of the location in meters.
@property (nonatomic) double xMeters;
/// The y coordinate of the location in meters.
@property (nonatomic) double yMeters;
/// The latitude of the location.
@property (nonatomic) double latitude;
/// The longitude of the location.
@property (nonatomic) double longitude;
/// The coordinates of the location in pixels.
@property (nonatomic, strong) Coordinate * _Nullable pixelCoordinates;
/// The floor number.
@property (nonatomic) NSInteger floor;
/// The surface of the location.
@property (nonatomic, copy) NSString * _Nonnull surfaceID;
/// The timestamp of the location.
@property (nonatomic) int64_t timestamp;
/// The type of the location.
/// Can be either “IPS” (Indoor Positioning System) or “GEO” (GPS/Geographic).
@property (nonatomic, copy) NSString * _Nonnull type;
/// The quality of the location.
/// Values range from 0 to 2, where 2 represents the best accuracy.
@property (nonatomic) NSInteger quality;
/// For IPS location type only. The maximum RSSI value recently observed.
/// Defaults to <code>-1000</code>.
@property (nonatomic) double maxRSSI;
/// For IPS location type only. The x-coordinate of the beacon with the maximum RSSI value.
/// Defaults to <code>0</code>.
@property (nonatomic) double beaconXForMaxRSSI;
/// For IPS location type only. The y-coordinate of the beacon with the maximum RSSI value.
/// Defaults to <code>0</code>.
@property (nonatomic) double beaconYForMaxRSSI;
/// For IPS location type only. The surface ID of the beacon with the maximum RSSI value.
/// Defaults to <code>00000000-0000-0000-0000-000000000000</code>.
@property (nonatomic, copy) NSString * _Nonnull surfaceIDForMaxRSSI;
/// For IPS location type only. The number of surfaces with at least one beacon observation.
@property (nonatomic) NSInteger observedSurfaces;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Location tracking mode determining whether the SDK tracks location in foreground only or both foreground and background.
typedef SWIFT_ENUM(NSInteger, LocationTrackingMode, open) {
/// Track location only when the app is in the foreground.
  LocationTrackingModeForeground = 0,
/// Track location both in foreground and background.
  LocationTrackingModeBackground = 1,
};

/// Represents the modules available in the CrowdConnected SDK.
typedef SWIFT_ENUM(NSInteger, Module, open) {
/// Geofencing / location module.
  ModuleGeo = 0,
/// Indoor Positioning System (IPS) module.
  ModuleIps = 1,
/// Core Bluetooth module for BLE interactions.
  ModuleCoreBluetooth = 2,
};

/// Receives lifecycle events from an active simulation session.
/// All methods are called on a background thread.
/// Marshal to the main thread if you need to update UI.
/// since:
/// 3.1.0
SWIFT_PROTOCOL("_TtP18CrowdConnectedCore18SimulationCallback_")
@protocol SimulationCallback
/// The AppSync subscription is live and simulation events will begin flowing.
- (void)onSimulationConnected;
/// A connection or subscription problem occurred (network error, expired token, invalid session, etc.).
/// \param reason A human-readable description of the failure.
///
- (void)onSimulationErrorWithReason:(NSString * _Nonnull)reason;
/// The session ended — either the server sent <code>SESSION_ENDED</code>, the subscription completed,
/// or the WebSocket closed unexpectedly.
/// Not called when you explicitly call <code>deactivateSimulation()</code>.
- (void)onSimulationDisconnected;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
